dashboard:
  create: true
  service:
    type: ClusterIP
  ingress: 
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: homelab-ca
    hosts:
      - name: chaos.homelab
        paths:
          - /
      
    tls:
      - secretName: chaos-mesh-tls
        hosts:
          - chaos.homelab
 
chaosDaemon:
  runtime: containerd
  socketPath: /run/containerd/containerd.sock

controllerManager:
  replicaCount: 1
  leaderElection:
    enabled: false