apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/logging/loki/values.yaml

    - repoURL: https://github.com/kingricky111/k8s-platform.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: logging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true