apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-homelab-tls
  namespace: monitoring
spec:
  secretName: grafana-homelab-tls
  commonName: grafana.homelab
  dnsNames:
    - grafana.homelab
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer